
update

install ant
install autoconf
install autogen
install automake
install bash
install ccache
install clisp
install closure-compiler
install cmake
install cmigemo
install colordiff
install coreutils
install ctags
install curl
install distcc
install figlet
install fontconfig
install fontforge
install freetype
install gauche
install gawk
install gfortran
install git
install giter8
install gnu-sed
install gnu-smalltalk
install graphviz
install htop-osx
install hub
install jq
install lua
install luajit
install lv
install lzlib
install lzo
install lzop
install maven
install memcached
install objective-caml
install openssl
install osxutils
install parallel
install pcre
install pkg-config
install proctools
install plt-racket
install python
install reattach-to-user-namespace
install redis
install rlwrap
install ruby
install sbt
install source-highlight
install spidermonkey
install sqlite
install tig
install tmux
install tree
install v8
install w3m
install wget
install xz
install zsh
