
update

install ant
install asciidoc
install autoconf
install autogen
install automake
install bash
install bdw-gc
install bison
install boost
install bsdmake
install cairo
install ccache
install clisp
install closure-compiler
install cmake
install cmigemo
install colordiff
install coreutils
install csshx
install ctags
install curl
install curl-ca-bundle
install dart
install distcc
install dmd
install dnsmasq
install docbook
install docbook-xsl
install figlet
install fontconfig
install fontforge
install freetype
install gauche
install gawk
install gd
install gdbm
install geoip
install gettext
install git
install giter8
install glib
install global
install gnu-sed
install gnu-smalltalk
install gradle
install graphviz
install groovy
install gstreamer
install guile
install htop-osx
install hub
install jq
install lua
install luajit
install lv
install lzlib
install lzo
install lzop
install maven
install memcached
install mercurial
install neko
install ninja
install nkf
install objective-caml
install openssl
install osxutils
install parallel
install pcre
install pkg-config
install proctools
install plt-racket
install python
install qcachegrind
install qt
install readline
install reattach-to-user-namespace
install redis
install rlwrap
install ruby
install sbt
install scons
install source-highlight
install spidermonkey
install sqlite
install tig
install tmux
install tree
install v8
install w3m
install watchman
install wget
install xz
install zsh
