#! /bin/bash

brew install ant
brew install autoconf
brew install autogen
brew install automake
brew install bash
brew install ccache
brew install clisp
brew install closure-compiler
brew install cmake
brew install colordiff
brew install coreutils
brew install ctags
brew install curl
brew install distcc
brew install fig
brew install figlet
brew install fontconfig
brew install fontforge
brew install freetype
brew install gauche
brew install gawk
brew install git
brew install giter8
brew install gnu-sed
brew install gnu-smalltalk
brew install graphviz
brew install htop-osx
brew install hub
brew install jq
brew install lua
brew install luajit
brew install lv
brew install lzlib
brew install lzo
brew install lzop
brew install maven
brew install memcached
brew install objective-caml
brew install openssl
brew install osxutils
brew install parallel
brew install pcre
brew install pkg-config
brew install proctools
brew install python
brew install reattach-to-user-namespace
brew install redis
brew install rlwrap
brew install ruby
brew install sqlite
brew install tig
brew install tmux
brew install tree
brew install wget
brew install xz
brew install zsh

exit 0;
