# coding: utf-8

task :default => [:tasks]

desc 'show this task list.'
task :tasks do
   Process::wait(spawn 'rake -T')
end

desc 'install bundler and execute `bundle install` for global.'
task :setup => [:bundler, :install]

desc 'install bundler.'
task :bundler do
  sh 'gem install bundler'
end

desc 'execute `bundle install` for global'
task :install do
  sh 'bundle install'
end

desc 'unlock by delete this `./Gemfile.lock`'
task :'unlock' do
  sh 'rm -f Gemfile.lock'
end

desc 'execute `bundle update`.'
task :update do
  sh 'bundle update'
end

desc 'uninstall non default gems.'
task :reset do
  `gem list -d`.split(/\n\n^(?=\w)/).each do |data|
    match = data.match(/(?<name>([^\s]+)) \((?<versions>.*)\)/)
    name = match[:name]
    versions = match[:versions].split(', ')
    if match = data.match(/^.*\(([\d\.]*),? ?default\): .*$/)
      next if match[1].empty?
      versions.delete(match[1] || versions[0])
    end
    versions.each { |v| sh "gem uninstall -Ix #{name} -v #{v}" }
  end
end
