# coding: utf-8

task :default => [:setup]

task :setup => [:bundler, :install]

task :bundler do
  sh 'gem install bundler'
end

task :install do
  sh 'bundle install'
end

task :update do
  sh 'bundle update'
end

task :reset do
  `gem list -d`.split(/\n\n^(?=\w)/).each do |data|
    match = data.match(/(?<name>([^\s]+)) \((?<versions>.*)\)/)
    name = match[:name]
    versions = match[:versions].split(', ')
    if match = data.match(/^.*\(([\d\.]*),? ?default\): .*$/)
      next if match[1].empty?
      versions.delete(match[1] || versions[0])
    end
    versions.each { |v| sh "gem uninstall -Ix #{name} -v #{v}" }
  end
end
