#! /bin/bash

git checkout $(git branch -a | perl -pe "s/remotes\/origin\///" | perl -pe "s/\*//" | perl -pe "s/^\s*//g" | sort | uniq | grep refs |fzf --preview \
    'git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit --date=relative origin/{}'
)

exit 0;
