# coding: utf-8

ProjectHome = File.expand_path(File.dirname(__FILE__))
ProjectName = "nix"


task :default => [:install]

desc "install #{ProjectName}"
task :install do
  sh "#{ProjectHome}/box/install.sh"
end

desc "uninstall #{ProjectName}"
task :uninstall do
  sh "#{ProjectHome}/box/uninstall.sh"
end

